/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.5/userguide/multi_project_builds.html
 */

rootProject.name = "kiwii-integration-test"

pluginManagement {
    repositories {
        maven{
          setUrl("https://artifactory.platform.manulife.io/artifactory/jcenter-cache")
          credentials {
            username = "zhandus"
            password = "APBFVgSz9aLR3Q9KXPFxFEjntuy"
          }
        }
        maven{
          setUrl("https://artifactory.platform.manulife.io/artifactory/plugins-release")
          credentials {
            username = "zhandus"
            password = "APBFVgSz9aLR3Q9KXPFxFEjntuy"
          }
        }
    }
}